{
 "title": "Java Runtime",
 "tags": [
  "java",
  "jvm",
  "runtime",
  "gc"
 ],
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(jvm_info, namespace)"
   },
   {
    "name": "app",
    "query": "label_values(jvm_info{namespace=~\"$namespace\"}, app)"
   },
   {
    "name": "pod",
    "query": "label_values(jvm_info{namespace=~\"$namespace\", app=~\"$app\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, app, pod) (jvm_threads_current{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, app, pod) (jvm_classes_currently_loaded{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, app, pod) (jvm_memory_heap_used_bytes{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "GC Overhead %",
   "type": "timeseries",
   "description": "Percentage of time spent in garbage collection. Alert threshold is typically 10%.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (namespace, app, pod) (jvm_gc_overhead{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"}) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Collections Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (namespace, app, pod) (rate(jvm_gc_collection_seconds_count{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Avg GC Pause Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (namespace, app, pod) (rate(jvm_gc_pause_seconds_sum{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"}[$__rate_interval])) / sum by (namespace, app, pod) (rate(jvm_gc_pause_seconds_count{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Allocation & Promotion Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (namespace, app, pod) (rate(jvm_gc_memory_allocated_bytes_total{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} allocated"
    },
    {
     "expr": "sum by (namespace, app, pod) (rate(jvm_gc_memory_promoted_bytes_total{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} promoted"
    }
   ]
  },
  { "title": "Heap Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Heap: Used vs Committed vs Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, app, pod) (jvm_memory_heap_used_bytes{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} used"
    },
    {
     "expr": "sum by (namespace, app, pod) (jvm_memory_heap_committed_bytes{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} committed"
    },
    {
     "expr": "sum by (namespace, app, pod) (jvm_memory_heap_max_bytes{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} max"
    }
   ]
  },
  {
   "title": "Live Data Size vs Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, app, pod) (jvm_gc_live_data_size_bytes{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} live"
    },
    {
     "expr": "sum by (namespace, app, pod) (jvm_gc_max_data_size_bytes{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} max"
    }
   ]
  },
  { "title": "Non-Heap Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Non-Heap: Used vs Committed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, app, pod) (jvm_memory_nonheap_used_bytes{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} used"
    },
    {
     "expr": "sum by (namespace, app, pod) (jvm_memory_nonheap_committed_bytes{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} committed"
    }
   ]
  },
  {
   "title": "Memory Pools (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, app, pod, pool) (jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} {{pool}}"
    }
   ]
  },
  { "title": "Buffers & Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Buffer Pool Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, app, pod, id) (jvm_buffer_memory_used_bytes{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} {{id}}"
    }
   ]
  },
  {
   "title": "JVM Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "jvm_info{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\"}"
    }
   ]
  }
 ]
}