{{- if .Values.rendererSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-renderer-token
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-renderer-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: {{ .Values.rendererSecret.itemName }}/credential
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
