{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thanos-objstore-config
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: thanos-objstore-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        objstore.yml: |
          type: S3
          config:
            bucket: "{{ `{{ .S3_BUCKET }}` }}"
            endpoint: "{{ `{{ .S3_ENDPOINT }}` }}"
            access_key: "{{ `{{ .AWS_ACCESS_KEY_ID }}` }}"
            secret_key: "{{ `{{ .AWS_SECRET_ACCESS_KEY }}` }}"
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: "{{ .Values.externalSecret.itemName }}/username"
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: "{{ .Values.externalSecret.itemName }}/password"
    - secretKey: S3_BUCKET
      remoteRef:
        key: "{{ .Values.externalSecret.itemName }}/S3 Configuration/bucket"
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: "{{ .Values.externalSecret.itemName }}/S3 Configuration/endpoint"
{{- end }}
