apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanos.fullname" . }}-query
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: query
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "thanos.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: query
  template:
    metadata:
      labels:
        {{- include "thanos.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: query
    spec:
      serviceAccountName: {{ include "thanos.fullname" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
        - name: query
          image: {{ include "thanos.image" . }}
          args:
            - query
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --endpoint={{ include "thanos.fullname" . }}-store.{{ .Release.Namespace }}.svc.cluster.local:10901
            {{- range .Values.query.extraEndpoints }}
            - --endpoint={{ . }}
            {{- end }}
          ports:
            - name: grpc
              containerPort: 10901
            - name: http
              containerPort: 10902
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
          resources:
            {{- toYaml .Values.query.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            readOnlyRootFilesystem: true
